### ISSUE TITLE
Divide By Zero (via quot, mod, rem) Crashes Joker

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#158]
Instead of raising a catchable exception, Joker ends up dying a horrible death:

```
user=> (/ 1 0)
<joker.core>:777:26: Eval error: Division by zero
Stacktrace:
  global <repl>:1:1
  core// <joker.core>:777:26
user=> (quot 1 0)
panic: runtime error: integer divide by zero [recovered]
	panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.processReplCommand.func1(0xc000937f60)
[...]
main.processReplCommand(0xc00055dc30, 0x2, 0xc00055dbf8, 0xc000937f60, 0x0)
	/home/craig/go/src/github.com/candid82/joker/main.go:133 +0x1d9
main.repl(0x2)
	/home/craig/go/src/github.com/candid82/joker/main.go:226 +0x50c
main.main()
	/home/craig/go/src/github.com/candid82/joker/main.go:689 +0x140a
$
```

(Discovered while working on https://github.com/candid82/joker/issues/131.)

**Comment by jcburley** [comment]
Same with `(rem 1 0)`, `(mod 3 0)`, maybe others.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/c518b466dbeb2461e131aad9792a9e0ff4dab79a
