### ISSUE TITLE
[linter parse] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by harold** [candid82/joker#214]
First, thanks for joker, we're loving it.

flycheck-joker panics on one particular file - sadly the file isn't open source, but I've chopped out a small bit (that makes no sense out of context) that still produces the error in joker's parser.

Interestingly commenting out the one `.preventDefault` line (as can be seen below), averts panic.

Hope this helps and that you have a great weekend.

```
harold@wintermute$ cat ./src/tech/ui/components/menu.cljc
(ns tech.ui.components.menu)

(defn- menu->list
  ([items close-and-nav depth]
   (into [:ol {:class (when (pos? depth) "submenu")}]
         (for [{:keys [text href sub-menu fn]} items]
           [:li.clickable (merge {}
                                 (when href
                                   {:on-click #(do
                                                 (.preventDefault %)
                                                 (close-and-nav href))}))]))))
```
```
harold@wintermute$ joker --lint ./src/tech/ui/components/menu.cljc
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c8e8f]

goroutine 1 [running]:
github.com/candid82/joker/core.TryParse.func1(0xc000c3ba90)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1704 +0x160
panic(0x7eed40, 0xea2cc0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/candid82/joker/core.parseSymbol(0xbe77a0, 0xc000a38390, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1642 +0x64f
github.com/candid82/joker/core.Parse(0xbe77a0, 0xc000a38390, 0xc000c3bb40, 0xc000a38390, 0x1)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1675 +0x3db
github.com/candid82/joker/core.parseVector(0xc0004ddaa0, 0xb, 0x4e, 0x3, 0x1, 0xc000da8b80, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:617 +0xc1
github.com/candid82/joker/core.Parse(0xbe6fc0, 0xc0004ddaa0, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1665 +0x763
github.com/candid82/joker/core.parseSeq(0xbe8b20, 0xc0005c8b00, 0xc000c3bb40, 0x0, 0x0, 0x30)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:608 +0x103
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0005c8b40, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1517 +0x5fb
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0005c8b40, 0xc000c3bb40, 0xbe5bc0, 0xc0005c8e40)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseMap(0xbe9980, 0xc0006fb680, 0xb, 0x47, 0x9, 0x24, 0xc000da8b80, 0xc000c3bb40, 0xc000c8fd80)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:634 +0x274
github.com/candid82/joker/core.Parse(0xbe65a0, 0xc0006fb680, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1668 +0x5c3
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc0005c8b80, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0005c8bc0, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1482 +0x18c1
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0005c8bc0, 0xc000c3bb40, 0xc0005c8bc0, 0xc0006fb6b0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0005c8e00, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1434 +0x2457
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0005c8e00, 0xc000c3bb40, 0xbe6c00, 0xc0005c8e00)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0005eb500, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0005eb500, 0xc000c3bb40, 0x0, 0x1)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseSeq(0xbe8b20, 0xc0005eb540, 0xc000c3bb40, 0x0, 0x0, 0x1b)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:608 +0x103
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0005eb5c0, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1517 +0x5fb
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0005eb5c0, 0xc000c3bb40, 0xc0005eb5c0, 0xc0005ebc40)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseVector(0xc0004dccc0, 0xb, 0x4a, 0x7, 0xc, 0xc000da8b80, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:617 +0xc1
github.com/candid82/joker/core.Parse(0xbe6fc0, 0xc0004dccc0, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1665 +0x763
github.com/candid82/joker/core.parseSeq(0xbe8b20, 0xc0005eb740, 0xc000c3bb40, 0x0, 0x0, 0xa)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:608 +0x103
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0005eb780, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1517 +0x5fb
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0005eb780, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc0005eba00, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
github.com/candid82/joker/core.parseLetLoop(0xbe6c60, 0xc0005ebac0, 0x5bd000, 0xc000c3bb40, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1064 +0xb5f
github.com/candid82/joker/core.parseLet(0xbe6c60, 0xc0005ebac0, 0xc000c3bb40, 0x4b)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:992 +0x44
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0005ebac0, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1441 +0x22f0
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0005ebac0, 0xc000c3bb40, 0xbe6c00, 0xc0005ebac0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0006699c0, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0006699c0, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc000669a00, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
github.com/candid82/joker/core.parseLetLoop(0xbe6c60, 0xc000669e00, 0x5bd000, 0xc000c3bb40, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1064 +0xb5f
github.com/candid82/joker/core.parseLet(0xbe6c60, 0xc000669e00, 0xc000c3bb40, 0x4b)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:992 +0x44
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000669e00, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1441 +0x22f0
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000669e00, 0xc000c3bb40, 0xbe6c00, 0xc000669e00)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc00069f080, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc00069f080, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc00069f200, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc00069f240, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1482 +0x18c1
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc00069f240, 0xc000c3bb40, 0xc00069f240, 0xc000636ba0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc00069f3c0, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1434 +0x2457
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc00069f3c0, 0xc000c3bb40, 0xbe6c00, 0xc00069f3c0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0006bfe00, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0006bfe00, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc0006bfe40, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
github.com/candid82/joker/core.parseLetLoop(0xbe6c60, 0xc0006bff00, 0x5bd000, 0xc000c3bb40, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1064 +0xb5f
github.com/candid82/joker/core.parseLet(0xbe6c60, 0xc0006bff00, 0xc000fd1b40, 0x4b)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:992 +0x44
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0006bff00, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1441 +0x22f0
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0006bff00, 0xc000c3bb40, 0xbe6c00, 0xc0006bff00)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc0006df240, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc0006df240, 0xc000c3bb40, 0xbe6c00, 0xc0006df240)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc00073c380, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc00073c380, 0xc000c3bb40, 0xbe6c00, 0xc00073c380)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000797d40, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000797d40, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc000797d80, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
github.com/candid82/joker/core.parseLetLoop(0xbe6c60, 0xc000797e40, 0x5bd001, 0xc000c3bb40, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1064 +0xb5f
github.com/candid82/joker/core.parseLoop(0xbe6c60, 0xc000797e40, 0xc000fd1b40, 0x4b)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:996 +0x44
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000797e40, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1443 +0x2293
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000797e40, 0xc000c3bb40, 0xbe6c00, 0xc000797e40)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000adbd40, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000adbd40, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc000adbdc0, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
github.com/candid82/joker/core.addArity(0xc0007f5980, 0xbe8b20, 0xc000adbe00, 0xc000c3bb40)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:813 +0x296
github.com/candid82/joker/core.parseFn(0xbe6c60, 0xc000adbe80, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:899 +0x429
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000adbe80, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1439 +0x234d
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000adbe80, 0xc000c3bb40, 0xbe6c00, 0xc000adbe80)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000adae40, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000adae40, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseSeq(0xbe8b20, 0xc000adaec0, 0xc000c3bb40, 0x0, 0x0, 0xa)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:608 +0x103
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000adaf00, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1517 +0x5fb
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000adaf00, 0xc000c3bb40, 0xbe6c00, 0xc000adaf00)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000ada0c0, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000ada0c0, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc000ada100, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
github.com/candid82/joker/core.addArity(0xc00041b280, 0xbe8b20, 0xc000ada140, 0xc000c3bb40)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:813 +0x296
github.com/candid82/joker/core.parseFn(0xbe6c60, 0xc000ada240, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:899 +0x429
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000ada240, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1439 +0x234d
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000ada240, 0xc000c3bb40, 0xbe6c00, 0xc000ada240)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000b10ec0, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000b10ec0, 0xc000c3bb40, 0xc000b10ec0, 0x1)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseLetLoop(0xbe6c60, 0xc000b111c0, 0x5bd000, 0xc000c3bb40, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1051 +0x67b
github.com/candid82/joker/core.parseLet(0xbe6c60, 0xc000b111c0, 0xc000fd1b40, 0x4b)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:992 +0x44
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000b111c0, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1441 +0x22f0
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000b111c0, 0xc000c3bb40, 0xbe6c00, 0xc000b111c0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000b398c0, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000b398c0, 0xc000c3bb40, 0xbe6c00, 0xc000b398c0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000c8e780, 0xc000fd1b40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1407 +0xbe
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000c8e780, 0xc000c3bb40, 0x0, 0x1)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseSeq(0xbe8b20, 0xc000c8e7c0, 0xc000c3bb40, 0x0, 0x0, 0x4)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:608 +0x103
github.com/candid82/joker/core.parseList(0xbe6c60, 0xc000c8e8c0, 0xc000c3bb40, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1517 +0x5fb
github.com/candid82/joker/core.Parse(0xbe6c60, 0xc000c8e8c0, 0xc000c3bb40, 0xece6b0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:1673 +0x508
github.com/candid82/joker/core.parseBody(0xbe8b20, 0xc000c8e900, 0xc000c3bb40, 0x0, 0x0, 0x0)
	/Users/candid/Documents/dev/personal/go/src/github.com/candid82/joker/core/parse.go:741 +0x155
```
```
harold@wintermute$ diff ./src/tech/ui/components/menu.cljc ./src/tech/ui/components/menu2.cljc
10c10
<                                                  (.preventDefault %)
---
>                                                  ;; (.preventDefault %)
```
```
harold@wintermute$ joker --lint ./src/tech/ui/components/menu2.cljc
./src/tech/ui/components/menu2.cljc:6:24: Parse warning: unused binding: text
./src/tech/ui/components/menu2.cljc:6:34: Parse warning: unused binding: sub-menu
./src/tech/ui/components/menu2.cljc:3:1: Parse warning: unused var menu->list
```

**Comment by candid82** [comment]
@harold thank you for reporting this! It's now fixed by https://github.com/candid82/joker/commit/9d0e9370c719a405f4645bd302fc2ba9a82f0cc7.
