### ISSUE TITLE
(joker.repl/apropos meta) Panics

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#271]
E.g.:

```
user=> (apropos meta)
panic: reflect: call of reflect.Value.Pointer on struct Value [recovered]
	panic: reflect: call of reflect.Value.Pointer on struct Value

goroutine 1 [running]:
main.processReplCommand.func1(0xc00092b320)
	/home/craig/go/src/github.com/candid82/joker/main.go:112 +0x2c5
panic(0x846f00, 0xc0008bde20)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
reflect.Value.Pointer(0x8b0fa0, 0xc000d38080, 0x99, 0x743cc0)
	/usr/local/go/src/reflect/value.go:1398 +0x18e
github.com/candid82/joker/core.Proc.Equals(0xbfb3f0, 0x8b0fa0, 0xc000d38080, 0xc000d38080)
	/home/craig/go/src/github.com/candid82/joker/core/object.go:819 +0x123
github.com/candid82/joker/core.IsInstance(0xc00000f5e0, 0xc83a80, 0xbfb3f0, 0x0)
	/home/craig/go/src/github.com/candid82/joker/core/object.go:1498 +0x6f
github.com/candid82/joker/core.glob..func57(0xc0008bde00, 0x2, 0x2, 0xc00096ad90, 0xc0008bde00)
	/home/craig/go/src/github.com/candid82/joker/core/procs.go:600 +0xa7
github.com/candid82/joker/core.Proc.Call(0xbfb538, 0xc0008bde00, 0x2, 0x2, 0xc0008bde00, 0x2)
	/home/craig/go/src/github.com/candid82/joker/core/object.go:807 +0x44
github.com/candid82/joker/core.(*CallExpr).Eval(0xc0007b9a90, 0xc000f46630, 0xc81860, 0xc0009bfec0)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:283 +0x122
github.com/candid82/joker/core.Eval(0xc816a0, 0xc0007b9a90, 0xc000f46630, 0x0, 0x0)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:107 +0x9b
github.com/candid82/joker/core.(*IfExpr).Eval(0xc0009bfec0, 0xc000f46630, 0xc818a0, 0xc0004cce00)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:387 +0x46
github.com/candid82/joker/core.Eval(0xc81860, 0xc0009bfec0, 0xc000f46630, 0x0, 0x0)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:107 +0x9b
github.com/candid82/joker/core.(*LetExpr).Eval(0xc0004cce00, 0xc000f46600, 0xc816a0, 0xc000f40370)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:409 +0x126
github.com/candid82/joker/core.Eval(0xc818a0, 0xc0004cce00, 0xc000f46600, 0x0, 0x0)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:107 +0x9b
github.com/candid82/joker/core.evalLoop(0xc0009847a0, 0x1, 0x1, 0xc000f46600, 0xc000f40370, 0xc0004bb8a8)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:360 +0xa7
github.com/candid82/joker/core.(*Fn).Call(0xc0009d8fc0, 0xc000d38050, 0x1, 0x1, 0x0, 0x0)
	/home/craig/go/src/github.com/candid82/joker/core/object.go:762 +0x6fa
github.com/candid82/joker/core.(*CallExpr).Eval(0xc000f40370, 0x0, 0x0, 0x0)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:283 +0x122
github.com/candid82/joker/core.Eval(0xc816a0, 0xc000f40370, 0x0, 0x0, 0x0)
	/home/craig/go/src/github.com/candid82/joker/core/eval.go:107 +0x9b
main.processReplCommand(0xc0004bbd60, 0x2, 0xc0004bbd28, 0xc00092b320, 0x0)
	/home/craig/go/src/github.com/candid82/joker/main.go:138 +0x1fb
main.repl(0x2)
	/home/craig/go/src/github.com/candid82/joker/main.go:231 +0x539
main.main()
	/home/craig/go/src/github.com/candid82/joker/main.go:720 +0x15e5
$
```

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/518baa12959c4dbbab1198b3b88907090fe59cc6
