### ISSUE TITLE
Joker fails to run

### ISSUE THREAD

**Issue by clee** [candid82/joker#295]
I cloned the latest `master` from github (revision `1399c2983df6c7d418d014642ec6037513026057`) and built with `go build` using go 1.13.4 on Debian testing.

When I run `./joker`, it reports:

```
panic: runtime error: slice bounds out of range [:8] with capacity 0

goroutine 1 [running]:
github.com/candid82/joker/core.extractInt(...)
	/home/clee/go/src/github.com/candid82/joker/core/pack.go:199
github.com/candid82/joker/core.UnpackHeader(0x0, 0x0, 0x0, 0xc0000e0150, 0xc00009a1e0, 0xc479a0, 0x7f24fb8cd008, 0x0)
	/home/clee/go/src/github.com/candid82/joker/core/pack.go:102 +0x7dd
github.com/candid82/joker/core.processData(0x0, 0x0, 0x0)
	/home/clee/go/src/github.com/candid82/joker/core/procs.go:1621 +0xf1
github.com/candid82/joker/core.ProcessCoreData()
	/home/clee/go/src/github.com/candid82/joker/core/procs.go:1631 +0x49
main.main()
	/home/clee/go/src/github.com/candid82/joker/main.go:554 +0x244
```

**Comment by jcburley** [comment]
Instead of `go build`, you might need to invoke `run.sh`, which (among other things) performs a crucial `go generate ./...` step.
