### ISSUE TITLE
(let [foo nil]) crashes Joker 1.3.0–1.3.5

### ISSUE THREAD

**Issue by dbohdan** [candid82/joker#502]
The crash does not affect version 1.2.0.

To reproduce the crash, create a file `killing.joke` :-) with the following code:

```clojure
(let [foo nil]) 
```

Then run Joker:

```
> ./joker killing.joke
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x791dd7]

goroutine 1 [running]:
github.com/candid82/joker/core.TryParse.func1()
	/scratch/joker/core/parse.go:1884 +0x16a
panic({0xa49be0?, 0x1028de0?})
	/usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
github.com/candid82/joker/core.IsEqualOrImplements(0x10c0700, 0x0)
	/scratch/joker/core/object.go:1638 +0x37
github.com/candid82/joker/core.IsInstance(0x10c0700, {0xcb7b00, 0xc0003e5ef0})
	/scratch/joker/core/object.go:1646 +0x76
github.com/candid82/joker/core.init.func124({0xc000303400, 0x2, 0xcb5de0?})
	/scratch/joker/core/procs.go:635 +0x6e
github.com/candid82/joker/core.Proc.Call(...)
	/scratch/joker/core/object.go:767
github.com/candid82/joker/core.(*CallExpr).Eval(0x1268f80, 0xc0004a6090)
	/scratch/joker/core/eval.go:291 +0x159
github.com/candid82/joker/core.Eval({0xcb5fa0?, 0x1268f80?}, 0x2fcfa0?)
	/scratch/joker/core/eval.go:110 +0x9e
github.com/candid82/joker/core.evalLoop({0x1043cf0, 0x1, 0x0?}, 0xc0004a6090)
	/scratch/joker/core/eval.go:368 +0x18c
github.com/candid82/joker/core.(*Fn).Call(0x10d5600, {0xc0002fcff0, 0x1, 0x1})
	/scratch/joker/core/object.go:708 +0x7b7
github.com/candid82/joker/core.(*CallExpr).Eval(0x12a9d80, 0xc0004a6030)
	/scratch/joker/core/eval.go:291 +0x159
github.com/candid82/joker/core.Eval({0xcb5fa0?, 0x12a9d80?}, 0x10?)
	/scratch/joker/core/eval.go:110 +0x9e
github.com/candid82/joker/core.(*IfExpr).Eval(0x1328e00, 0xc0004a6030)
	/scratch/joker/core/eval.go:384 +0x32
github.com/candid82/joker/core.Eval({0xcb5f20?, 0x1328e00?}, 0x30?)
	/scratch/joker/core/eval.go:110 +0x9e
github.com/candid82/joker/core.evalBody(...)
	/scratch/joker/core/eval.go:359
github.com/candid82/joker/core.(*DoExpr).Eval(0x0?, 0xc0004a6030)
	/scratch/joker/core/eval.go:380 +0x6a
github.com/candid82/joker/core.Eval({0xcb6060?, 0x1254a00?}, 0x3f69c610?)
	/scratch/joker/core/eval.go:110 +0x9e
github.com/candid82/joker/core.evalLoop({0x10b3a40, 0x2, 0x40?}, 0xc0004a6030)
	/scratch/joker/core/eval.go:368 +0x18c
github.com/candid82/joker/core.(*Fn).Call(0x110b080, {0xc000332a40, 0x3, 0x4})
	/scratch/joker/core/object.go:744 +0x50f
github.com/candid82/joker/core.(*MacroCallExpr).Eval(0xc0001a6ea0?, 0xc0003bf0f8?)
	/scratch/joker/core/eval.go:424 +0x2b
github.com/candid82/joker/core.Eval({0xcb6360?, 0xc0001a6ea0?}, 0xc000332940?)
	/scratch/joker/core/eval.go:110 +0x9e
github.com/candid82/joker/core.macroexpand1({0xcb9f10, 0xc000332940}, 0xc0003bfaa0)
	/scratch/joker/core/parse.go:1290 +0x5a5
github.com/candid82/joker/core.parseList({0xcb74d0, 0xc000332940}, 0xc0003bfaa0)
	/scratch/joker/core/parse.go:1558 +0xb7
github.com/candid82/joker/core.Parse({0xcb74d0, 0xc000332940}, 0xc0003bfaa0)
	/scratch/joker/core/parse.go:1853 +0x436
github.com/candid82/joker/core.TryParse({0xcb74d0?, 0xc000332940?}, 0x18?)
	/scratch/joker/core/parse.go:1888 +0x65
github.com/candid82/joker/core.ProcessReader(0xc000181360, {0x7ffe85bfefc2?, 0xc?}, 0x3)
	/scratch/joker/core/procs.go:1818 +0x2d2
main.processFile({0x7ffe85bfefc2?, 0xc?}, 0x3)
	/scratch/joker/main.go:134 +0xa0e
main.main()
	/scratch/joker/main.go:883 +0x17c8
```

**Comment by candid82** [comment]
@dbohdan Thank you for reporting! I am not able to reproduce the issue with the latest version of Joker on macOS. What OS are you on? Also, are you using the pre-built binary or did you build Joker binary yourself? Any additional info would be helpful.

**Comment by dbohdan** [comment]
Sorry, this was my mistake. I encountered the crash on Ubuntu and NetBSD, which convinced me it was a project bug. While I thought I was building Joker from a clean checkout on both systems, I actually wasn't.

Here is how to reproduce the mistake I made:

```shell
git checkout v1.2.0
./run.sh --version
git checkout v1.3.5
# No `go generate ./...` step.
go build
./joker killing.joke
# Crashes.
```
I am surprised it built and partially worked.

I'll be sure to include the OS and whether I built the binary myself next time.

**Comment by candid82** [comment]
@dbohdan No worries, glad it was not an actual bug in Joker :)
